name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1

      # Build both webapp and newapp
      # - name: Build webapp
      #   run: |
      #     cd webapp
      #     npm install
      #     npm run build
      #     mv dist ../webapp-dist

      - name: Build newapp
        run: |
          cd newapp
          npm install
          npm run build
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "newapp/dist/"
          name: newapp

      - name: update CNAME
        run: echo "www.improwised.com" > newapp/dist/CNAME
      # Combine both apps into a single deployment folder
      # - name: Combine build artifacts
      #   run: |
      #     mkdir combined-dist
      #     mv webapp-dist/* combined-dist/
      #     mkdir combined-dist/newapp
      #     mv newapp-dist/* combined-dist/newapp/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "newapp/dist/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
