name: AppDir

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: webapp
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.13.1

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy improwised-new-website1 to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
          branch: gh-pages
          folder: webapp/dist
          message: "Deploy newapp-${{ github.run_number }}"
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./webapp/dist        
  
