name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: webapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy improwised-new-website1 to GitHub Pages
        id: deployment2
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: webapp/dist
          message: "Deploy webapp-${{ github.run_number }}"
